### ISSUE TITLE
Build, train and deploy succeed but query error.

### ISSUE THREAD

**Issue by cailurus** [EmergentOrder/template-scala-topic-model-LDA#4]
Build phase was good.
In Train phase got:
[WARN] [BLAS] Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
[WARN] [BLAS] Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS

and
[INFO] [CoreWorkflow$] Training completed successfully.

Deploy was good.

but Query with text:
java.lang.NoSuchMethodError: org.apache.spark.mllib.clustering.LocalLDAModel.topicDistributions(Lorg/apache/spark/rdd/RDD;)Lorg/apache/spark/rdd/RDD;

**Comment by EmergentOrder** [comment]
Looks like you are using an older version of Spark. If you installed the latest PredictionIO using the install script, you should have Spark 1.5.1 which would work.

topicDistributions() was only introduced in Spark 1.5.0 : 
https://spark.apache.org/docs/1.5.0/api/java/org/apache/spark/mllib/clustering/LocalLDAModel.html
